list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/Q3111/Solution.cpp)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/Q3151/Solution.cpp)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/Q3174/Solution.cpp)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/Q3177/Solution.cpp)
