list(APPEND INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR}/Chap06/Figure6_1)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/Chap06/Figure6_1/List.h)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/Chap06/Figure6_1/List.cpp)
